### PR TITLE
Add termguicolors support for lightline

### PR DESCRIPTION
**Pull request by sainnhe**
Just like [#93](https://github.com/edkolev/tmuxline.vim/pull/93), this PR check if `termguicolors` is set, and then create a color scheme use true colors.

### CODE REVIEW

**Comment by sainnhe** [comment]
Oh sorry, I committed without thinking seriously. The third value is used to specify bold/italic etc, I simply ignore this value.

**Comment by sainnhe** [comment]
Tested on my machine, should work fine now.

**Comment by fr3fou** [comment]
Is there any way for me to use this while waiting for it to get merged?
I'm currently having trouble getting Tmuxline to show the appropriate colorscheme, it looks like this:

image

**Comment by fr3fou** [comment]
Seeing you updated your fork, I guess I could try using your fork temporarily?

**Comment by fr3fou** [comment]
Yep! That worked! Hopefully we see this merged into here :)

**Comment by sainnhe** [comment]
Of course, I've merged it to support new syntax in tmux2.9, you can now use the master branch of my fork.

**Comment by sainnhe** [comment]
I'm going to close this PR because I think #109 does better.

**Pull request closed without merging**
