### PR TITLE
Adapt generated tmux config to new tmux 2.9 syntax

### LINKED ISSUE #100: tmux 1.9 compatibility
> The individual -fg, -bg and -attr options have been removed; they
> were superseded by -style options in tmux 1.9.

### LINKED ISSUE #102: tmux 2.9-1 issues
This are the issues ..
```
/home/archangel/.tmuxline.conf:25: invalid or unknown command: set -g status-left "#[fg=colour18,bg=colour4,bold] #S #[fg=colour4,bg=colour19,nobold,nounderscore,noitalics]#[fg=colour7,bg=colour19] #I:#P > #W #[fg=colour19,bg=colour18,nobold,nounderscore,noitalics]#[fg=colour7,bg=colour18] #(whoami) > #(uptime | cut -d \" \" -f 2,3| sed -i \"s/[
/home/archangel/.tmuxline.conf:6: invalid option: status-attr
/home/archangel/.tmuxline.conf:7: invalid option: message-command-bg
/home/archangel/.tmuxline.conf:9: invalid option: pane-active-border-fg
/home/archangel/.tmuxline.conf:11: invalid option: message-command-fg
/home/archangel/.tmuxline.conf:12: invalid option: pane-border-fg
/home/archangel/.tmuxline.conf:13: invalid option: message-bg
/home/archangel/.tmuxline.conf:14: invalid option: status-left-attr
/home/archangel/.tmuxline.conf:15: invalid option: status-right-attr
/home/archangel/.tmuxline.conf:17: invalid option: message-fg
/home/archangel/.tmuxline.conf:18: invalid option: window-status-fg
/home/archangel/.tmuxline.conf:19: invalid option: window-status-attr
/home/archangel/.tmuxline.conf:20: invalid option: window-status-activity-bg
/home/archangel/.tmuxline.conf:21: invalid option: window-status-activity-attr
/home/archangel/.tmuxline.conf:22: invalid option: window-status-activity-fg
/home/archangel/.tmuxline.conf:24: invalid option: window-status-bg
```

here is  the file

```
# This tmux statusbar config was created by tmuxline.vim
# on Fri, 26 Apr 2019

set -g status-justify "centre"
set -g status "on"
set -g status-attr "none"
set -g message-command-bg "colour19"
set -g status-left-length "100"
set -g pane-active-border-fg "colour4"
set -g status-bg "colour18"
set -g message-command-fg "colour7"
set -g pane-border-fg "colour19"
set -g message-bg "colour19"
set -g status-left-attr "none"
set -g status-right-attr "none"
set -g status-right-length "100"
set -g message-fg "colour7"
setw -g window-status-fg "colour7"
setw -g window-status-attr "none"
setw -g window-status-activity-bg "colour18"
setw -g window-status-activity-attr "none"
setw -g window-status-activity-fg "colour4"
setw -g window-status-separator ""
setw -g window-status-bg "colour18"
set -g status-left "#[fg=colour18,bg=colour4,bold] #S #[fg=colour4,bg=colour19,nobold,nounderscore,noitalics]#[fg=colour7,bg=colour19] #I:#P > #W #[fg=colour19,bg=colour18,nobold,nounderscore,noitalics]#[fg=colour7,bg=colour18] #(whoami) > #(uptime | cut -d \" \" -f 2,3| sed -i \"s/[
```

### PR DESCRIPTION
**Pull request by He-Ro**
Closes #102
Closes #100

Inspired by @secuvim in #102 
I do not know if this is all that is needed, but it worked for me.

### CODE REVIEW

**Comment by secuvim** [comment]
This would break the backwards compatibility for users with tmux versions < 1.9.

To keep the backwards compatibility you could wrap your changes in something like:

```
let tmux_version = system("tmux -V")
    if (tmux_version < 'tmux 1.9')
        let misc_options = ...
        let win_options = ...
    else
        let misc_options = ...
        let win_options = ...
    elseif
```

This is just a suggestion as I am not the maintainer of this package.

@He-Ro Thanks for implementing a fix.

@edkolev What is your opinion on this?

**Comment by khalsah** [comment]
Some of the presets appear to write into `win_options['window-status-activity-attr']` which causes problems if you're using one of those presets:

- https://github.com/edkolev/tmuxline.vim/blob/c8a0295eb34bf11447779a5a203fd472147788a7/autoload/tmuxline/presets/powerline.vim#L26
- https://github.com/edkolev/tmuxline.vim/blob/c8a0295eb34bf11447779a5a203fd472147788a7/autoload/tmuxline/presets/nightly_fox.vim#L15
- https://github.com/edkolev/tmuxline.vim/blob/c8a0295eb34bf11447779a5a203fd472147788a7/autoload/tmuxline/presets/crosshair.vim#L23

**Comment by edkolev** [comment]
@He-Ro amazing work on this, thanks! Could you also:
- git grep and change everywhere `window-status-activity-attr` => `window-status-activity-style`
- add yourself to the CONTRIBUTORS.md in the root of the project

@khalsah good catch!

> This would break the backwards compatibility for users with tmux versions < 1.9.
>
> @edkolev What is your opinion on this?

I'm fine with breaking compatibility for tmux <1.9 - it's been more than 5 years since 1.9 was released. Adding a conditional in the vim script would not work when you share the generated tmux conf file between machines with different versions of tmux.

**Comment by He-Ro** [comment]
Added the requested changes.

Also found a mention of attr in the README.

**Comment by shrop** [comment]
Thanks for working on this. Just noting https://github.com/tmux/tmux/wiki/FAQ#how-do-i-translate--fg--bg-and--attr-options-into--style-options and curious if this was a known issue here.

**Comment by edkolev** [comment]
> and curious if this was a known issue here

Could you clarify the question? The link is pointing to a wiki entry about migration; the wiki entry isn't a know issue

**Comment by shrop** [comment]
Gotcha, maybe this issue isn't related. I had to manually fix up some tmuxline generated settings to comply with the Tmux 2.9 Syntax ralated to -style and -attr. If thosed fixes have been merged in, I can try to run a new snapshot and see if that works.

**Comment by edkolev** [comment]
This PR addresses exactly this - the `*-fg/bg` to `*-style` migration. And yes, you should be able to create a snapshot which works with the lates tmux.

**Pull request merged**
